name: Build Docker Container and Push to ECR

on: [push]

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      
      - name: Get ECR Credentials
        run: aws ecr-public get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin public.ecr.aws/s3h7a9e5
      
      - name: Build container
        run: |
          docker build --build-arg AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
                       --build-arg AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
                       --tag hangenyuu/inference .
      - name: Tag image
        run: docker tag hangenyuu/inference:latest public.ecr.aws/s3h7a9e5/food102:latest
      
      - name: Push2ECR
        run: docker push public.ecr.aws/s3h7a9e5/food102:latest